# [START_EXCLUDE]
# Copyright 2015 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [END_EXCLUDE]
#
# This sample has manual_scaling set to 1.
#
runtime: java11

handlers:
- url: /.*
  script: this field is required, but ignored

#manual_scaling:
#  instances: 1
basic_scaling:  
  max_instances: 1
  idle_timeout: 10m

# specify base image
FROM adoptopenjdk/openjdk11:slim

# install Maven on top of base image
RUN apt-get update && apt-get install -y --no-install-recommends maven

# define working directory
WORKDIR /app

# copy over app files
COPY pom.xml .
COPY src src

# expose default Spring Boot port 8080
EXPOSE 8080

# define default command
CMD ["/bin/sh", "-c", "mvn spring-boot:run"]